main: GetMap
name: GetMap
version: 1.0
author: ychenfo
description: Get the map in a specific region
commands:
   startRec:
      description: start rec related log
      usage: /startRec
   endRec:
      description: end rec related log
      usage: /endRec